# Generated by Django 5.1.1 on 2025-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_products_options_products_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
